title: Noob Coder
description: [Normal Guy, Love programming]
repository: beohoang98/beohoang98.github.io
baseurl: ""

fb_name: beo.hoang395
github_name: beohoang98
linkedin_name: an-hoang98

sass:
  sass_dir: _sass
  style: compressed

highlighter: rouge

markdown: kramdown
plugins:
  - jekyll-feed